-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS staging."softcartDimDate"
(
    dateid integer NOT NULL,
    month smallint,
    monthname character varying(30)[],
    year smallint,
    day smallint,
    weekday character varying(30),
    quarter smallint,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS staging."softcartDimCategory"
(
    categoryid integer NOT NULL,
    categoryname character varying(50),
    PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS staging."softcartDimItem"
(
    itemid integer NOT NULL,
    itemname character varying(50),
    PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS staging."softcartDimCountry"
(
    countryid integer NOT NULL,
    countryname character varying(50),
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS staging."softcartFactSales"
(
    id integer NOT NULL,
    dateid integer NOT NULL,
    itemid integer NOT NULL,
    countryid integer NOT NULL,
    categoryid integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD CONSTRAINT fk_category FOREIGN KEY (categoryid)
    REFERENCES staging."softcartDimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD CONSTRAINT fk_item FOREIGN KEY (itemid)
    REFERENCES staging."softcartDimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD CONSTRAINT fk_country FOREIGN KEY (countryid)
    REFERENCES staging."softcartDimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS staging."softcartFactSales"
    ADD CONSTRAINT fk_date FOREIGN KEY (dateid)
    REFERENCES staging."softcartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;